<%@LANGUAGE="VBSCRIPT" CODEPAGE="65001"%>
<!--#include file="../funciones2.asp"-->
<%
idUsuario = Trim(request("idUsuario"))
perfil = Trim(request("idPerfil"))

codSucursal = ""
sqlSuc = ""

	if (perfil = 2) then
		sqlSucs = ""
		'sqlSucs = sqlSucs & "select id_sucursal "
		'sqlSucs = sqlSucs & "from SUC_zonales_sucursal "
		'sqlSucs = sqlSucs & "where id_zonal =  " & idUsuario

		sqlSucs = sqlSucs & "select id_sucursal "
		sqlSucs = sqlSucs & "from SUC_usuario_sucursal "
		sqlSucs = sqlSucs & "where id_usuario =  " & idUsuario
		
		set rsSucs = db.execute(sqlSucs)		
		if not rsSucs.eof then
		  dataSucs = rsSucs.GetRows()
		end if
		for y=0 to ubound(dataSucs,2)
		  codSucursal = codSucursal & dataSucs(0,y) & ","
		next
		codSucursal = left(codSucursal, (len(codSucursal)-1))		
		rsSucs.close: set rsSucs = nothing 
		
		sqlSuc = ""
		sqlSuc = sqlSuc & "and id_sucursal in ("&codSucursal&")"
	end if
	
	if (perfil = 55) then
		sqlSucs = ""
		sqlSucs = sqlSucs & "select id_sucursal "
		sqlSucs = sqlSucs & "from SUC_zonales_comercial_sucursal "
		sqlSucs = sqlSucs & "where id_zonal =  " & idUsuario
		
		set rsSucs = db.execute(sqlSucs)		
		if not rsSucs.eof then
		  dataSucs = rsSucs.GetRows()
		end if
		for y=0 to ubound(dataSucs,2)
		  codSucursal = codSucursal & dataSucs(0,y) & ","
		next
		codSucursal = left(codSucursal, (len(codSucursal)-1))		
		rsSucs.close: set rsSucs = nothing 
		
		sqlSuc = ""
		sqlSuc = sqlSuc & "and id_sucursal in ("&codSucursal&")"
	end if
	
	if (perfil = 66) then
		sqlSucs = ""
		sqlSucs = sqlSucs & "select id_sucursal "
		sqlSucs = sqlSucs & "from SUC_zonales_comercial_mas_sucursal "
		sqlSucs = sqlSucs & "where id_zonal =  " & idUsuario
		
		set rsSucs = db.execute(sqlSucs)		
		if not rsSucs.eof then
		  dataSucs = rsSucs.GetRows()
		end if
		for y=0 to ubound(dataSucs,2)
		  codSucursal = codSucursal & dataSucs(0,y) & ","
		next
		codSucursal = left(codSucursal, (len(codSucursal)-1))		
		rsSucs.close: set rsSucs = nothing 
		
		sqlSuc = ""
		sqlSuc = sqlSuc & "and id_sucursal in ("&codSucursal&")"
	end if
	

	sql = ""
	sql = sql & "select "	 
	sql = sql & "(select COUNT(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal "
	sql = sql & "where tipo_personal='Cajero' and tipo = 'titular' "&sqlSuc&") as cajerotitular "
	sql = sql & ", "
	sql = sql & "(select count(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal "
	sql = sql & "where tipo_personal='Cajero' and tipo = 'reemplazo' "&sqlSuc&") as cajeroreemplazo "
	sql = sql & ", "
	sql = sql & "(select COUNT(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal "
	sql = sql & "where tipo_personal='CAJERO ADICIONAL' and tipo = 'reemplazo' "&sqlSuc&") as cajeroadicional "
	sql = sql & ", "
	sql = sql & "(select COUNT(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal "
	sql = sql & "where tipo_personal in ('Cajero','CAJERO ADICIONAL') and asistencia is not null "&sqlSuc&") as cajerosregistrados "
	sql = sql & ", "
	sql = sql & "(select COUNT(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal "
	sql = sql & "where tipo_personal in ('Cajero','CAJERO ADICIONAL') and asistencia is not null and asistencia='si' "&sqlSuc&") as cajerospresentes "
	sql = sql & ", "
	sql = sql & " ( " 
	sql = sql & " select COUNT(*) "
	sql = sql & " from SUC_sucursal_asistencia_personal "
	sql = sql & " where tipo_personal in ('Cajero','CAJERO ADICIONAL') "
	sql = sql & " and asistencia is not null "
	sql = sql & " and asistencia='no' "
	sql = sql & " and rut_personal not in ( "
	sql = sql & " select a.rut_titular "
	sql = sql & " from SUC_sucursal_reemplazos a  "
	sql = sql & " inner join SUC_sucursal_asistencia_personal b on " 
	sql = sql & " a.rut_reemp = b.rut_personal and a.bt_sucursal = b.bt_sucursal "
	sql = sql & " where a.id_cargo in (1,6) and a.rut_titular not in ('', '1-9') "
	sql = sql & " and b.asistencia = 'si' ) and rut_personal not in ( "
	sql = sql & " select a.rut_reemp "
	sql = sql & " from SUC_sucursal_reemplazos a "
	sql = sql & " where cast(a.hora_ingreso as time) > cast(GETDATE() as time) "
	sql = sql & " and a.id_cargo in (1,6) and a.rut_titular not in ('', '1-9')) "
	sql = sql & " "&sqlSuc&" ) as cajerosausentes "
	sql = sql & ", "
	sql = sql & "(select COUNT(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal (nolock) "
	sql = sql & "where tipo_personal='Asesor de Clientes' and tipo = 'titular' "&sqlSuc&") as asesortitular "
	sql = sql & ", "
	sql = sql & "(select COUNT(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal (nolock) "
	sql = sql & "where tipo_personal='Asesor de Clientes' and tipo = 'reemplazo' "&sqlSuc&") as asesoreemplazo "
	sql = sql & ", "
	sql = sql & "(select COUNT(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal (nolock)  "
	sql = sql & "where tipo_personal='Asesor de Clientes' and asistencia is not null "&sqlSuc&") as asesoresregistrados "
	sql = sql & ", "
	sql = sql & "(select COUNT(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal (nolock) "
	sql = sql & "where tipo_personal='Asesor de Clientes' and asistencia is not null and asistencia='si' "&sqlSuc&") as asesorespresentes "
	sql = sql & ", "
	sql = sql & " ( select COUNT(*) "
	sql = sql & " from SUC_sucursal_asistencia_personal  "
	sql = sql & " where tipo_personal in ('Anfitrion','Asesor de Clientes')  "
	sql = sql & " and asistencia is not null  "
	sql = sql & " and asistencia='no' "
	sql = sql & " and rut_personal not in ( "
	sql = sql & " select a.rut_titular "
	sql = sql & " from SUC_sucursal_reemplazos a  "
	sql = sql & " inner join SUC_sucursal_asistencia_personal b " 
	sql = sql & " on a.rut_reemp = b.rut_personal and a.bt_sucursal = b.bt_sucursal "
	sql = sql & " where a.id_cargo in (3) and a.rut_titular not in ('', '1-9') "
	sql = sql & " and b.asistencia = 'si' ) and rut_personal not in ( "
	sql = sql & " select a.rut_reemp "
	sql = sql & " from SUC_sucursal_reemplazos a "
	sql = sql & " where cast(a.hora_ingreso as time) > cast(GETDATE() as time) "
	sql = sql & " and a.id_cargo in (3) and a.rut_titular not in ('', '1-9')) "
	sql = sql & " "&sqlSuc&" ) as asesoresausentes "
	sql = sql & ", "
	sql = sql & "(select COUNT(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal (nolock) "
	sql = sql & "where tipo_personal='Paramedico' and tipo = 'titular' "&sqlSuc&") as paramedicotitular "
	sql = sql & ", "
	sql = sql & "(select COUNT(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal (nolock) "
	sql = sql & "where tipo_personal='Paramedico' and tipo = 'reemplazo' "&sqlSuc&") as paramedicoreemplazo "
	sql = sql & ", "
	sql = sql & "(select COUNT(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal (nolock) "
	sql = sql & "where tipo_personal='Paramedico' and asistencia is not null "&sqlSuc&") as paramedicosregistrados "
	sql = sql & ", "
	sql = sql & "(select COUNT(*) "
	sql = sql & "from SUC_sucursal_asistencia_personal (nolock) " 
	sql = sql & "where tipo_personal='Paramedico' and asistencia is not null and asistencia='si' "&sqlSuc&") as paramedicospresentes "
	sql = sql & ", "
	sql = sql & " (select COUNT(*) "
	sql = sql & " from SUC_sucursal_asistencia_personal  "
	sql = sql & " where tipo_personal in ('Paramedico')  "
	sql = sql & " and asistencia is not null "
	sql = sql & " and asistencia='no' "
	sql = sql & " and rut_personal not in ( "
	sql = sql & " select a.rut_titular "
	sql = sql & " from SUC_sucursal_reemplazos a "
	sql = sql & " inner join SUC_sucursal_asistencia_personal b "
	sql = sql & " on a.rut_reemp = b.rut_personal and a.bt_sucursal = b.bt_sucursal "
    sql = sql & " where a.id_cargo in (2) and a.rut_titular not in ('', '1-9') "
	sql = sql & " and b.asistencia = 'si')  and rut_personal not in ( "
	sql = sql & " select a.rut_reemp "
	sql = sql & " from SUC_sucursal_reemplazos a "
	sql = sql & " where cast(a.hora_ingreso as time) > cast(GETDATE() as time) "
	sql = sql & " and a.id_cargo in (2) and a.rut_titular not in ('', '1-9')) "
	sql = sql & " "&sqlSuc&") as paramedicosausentes "
	sql = sql & ", "
	sql = sql & "(select sum(z.titulares_dot) from ( "
	sql = sql & "select *, case when y.total >= y.titulares_dot then 0 else y.titulares_a + y.reemp_a  end ausencia from ( "
	sql = sql & "select *, ((titulares_p)+(reemp_p)) as total from ( "
	sql = sql & "	select a.cod_bantotal,  "
	sql = sql & "		   count(*) titulares_dot "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b where a.cod_bantotal = b.cod_bantotal and b.asistencia = 'si' and b.tipo_suc = 'titular'),0) as titulares_p "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b where a.cod_bantotal = b.cod_bantotal and (b.asistencia = 'no' or b.asistencia is null) and b.tipo_suc = 'titular'),0) as titulares_a "
	sql = sql & "		   ,isnull((select COUNT(gr.guardia_rut_titular) "
	sql = sql & "		   			from SUC_sucursal_guardias_r gr  "
	sql = sql & "		   			where gr.guardia_rut_titular = a.guardia_rut  "
	sql = sql & "		   			and gr.cod_bantotal = a.cod_bantotal  "
	sql = sql & "		   			and CONVERT(date,gr.desde) <= CONVERT(date,GETDATE())),0)as reemplazos_dot "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b  "
	sql = sql & "					inner join SUC_sucursal_guardias_r gr on gr.guardia_rut = b.guardia_rut and gr.cod_bantotal = b.cod_bantotal "
	sql = sql & "					where a.cod_bantotal = b.cod_bantotal and b.asistencia = 'si' and b.tipo_suc = 'reemplazo'  "
	sql = sql & "					and CONVERT(date,desde) <= CONVERT(date,GETDATE())),0) as reemp_p, "
	sql = sql & "		   isnull((select count(*) from SUC_sucursal_guardias_asistencia b  "
	sql = sql & "					inner join SUC_sucursal_guardias_r gr on gr.guardia_rut = b.guardia_rut and gr.cod_bantotal = b.cod_bantotal "
	sql = sql & "					where a.cod_bantotal = b.cod_bantotal and (b.asistencia = 'no' or b.asistencia is null) and b.tipo_suc = 'reemplazo' "
	sql = sql & "					and CONVERT(date,desde) <= CONVERT(date,GETDATE()) "
	sql = sql & "					),0) as reemp_a "
	sql = sql & "	from SUC_sucursal_guardias_t a "
	sql = sql & "	group by a.cod_bantotal,a.guardia_rut "
	sql = sql & ") as z ) as y  "
	sql = sql & ") as z "&sqlSuc&") as guardiastitulares "
	sql = sql & ", "
	sql = sql & "(select sum(z.reemplazos_dot) from ( "
	sql = sql & "select *, case when y.total >= y.titulares_dot then 0 else y.titulares_a + y.reemp_a  end ausencia from ( "
	sql = sql & "select *, ((titulares_p)+(reemp_p)) as total from ( "
	sql = sql & "	select a.cod_bantotal,  "
	sql = sql & "		   count(*) titulares_dot "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b where a.cod_bantotal = b.cod_bantotal and b.asistencia = 'si' and b.tipo_suc = 'titular'),0) as titulares_p "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b where a.cod_bantotal = b.cod_bantotal and (b.asistencia = 'no' or b.asistencia is null) and b.tipo_suc = 'titular'),0) as titulares_a "
	sql = sql & "		   ,isnull((select COUNT(gr.guardia_rut_titular) "
	sql = sql & "		   			from SUC_sucursal_guardias_r gr  "
	sql = sql & "		   			where gr.guardia_rut_titular = a.guardia_rut  "
	sql = sql & "		   			and gr.cod_bantotal = a.cod_bantotal  "
	sql = sql & "		   			and CONVERT(date,gr.desde) <= CONVERT(date,GETDATE())),0)as reemplazos_dot "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b  "
	sql = sql & "					inner join SUC_sucursal_guardias_r gr on gr.guardia_rut = b.guardia_rut and gr.cod_bantotal = b.cod_bantotal "
	sql = sql & "					where a.cod_bantotal = b.cod_bantotal and b.asistencia = 'si' and b.tipo_suc = 'reemplazo'  "
	sql = sql & "					and CONVERT(date,desde) <= CONVERT(date,GETDATE())),0) as reemp_p, "
	sql = sql & "		   isnull((select count(*) from SUC_sucursal_guardias_asistencia b  "
	sql = sql & "					inner join SUC_sucursal_guardias_r gr on gr.guardia_rut = b.guardia_rut and gr.cod_bantotal = b.cod_bantotal "
	sql = sql & "					where a.cod_bantotal = b.cod_bantotal and (b.asistencia = 'no' or b.asistencia is null) and b.tipo_suc = 'reemplazo' "
	sql = sql & "					and CONVERT(date,desde) <= CONVERT(date,GETDATE()) "
	sql = sql & "					),0) as reemp_a "
	sql = sql & "	from SUC_sucursal_guardias_t a "
	sql = sql & "	group by a.cod_bantotal,a.guardia_rut "
	sql = sql & ") as z ) as y  "
	sql = sql & ") as z "&sqlSuc&")as guardiasreemp "
    sql = sql & ", "
	sql = sql & "(select count(z.titulares_dot)+sum(z.reemplazos_dot) from ( "
	sql = sql & "select *, case when y.total >= y.titulares_dot then 0 else y.titulares_a + y.reemp_a  end ausencia from ( "
	sql = sql & "select *, ((titulares_p)+(reemp_p)) as total from ( "
	sql = sql & "	select a.cod_bantotal,  "
	sql = sql & "		   count(*) titulares_dot "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b where a.cod_bantotal = b.cod_bantotal and b.asistencia = 'si' and b.tipo_suc = 'titular'),0) as titulares_p "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b where a.cod_bantotal = b.cod_bantotal and (b.asistencia = 'no' or b.asistencia is null) and b.tipo_suc = 'titular'),0) as titulares_a "
	sql = sql & "		   ,isnull((select COUNT(gr.guardia_rut_titular) "
	sql = sql & "		   			from SUC_sucursal_guardias_r gr  "
	sql = sql & "		   			where gr.guardia_rut_titular = a.guardia_rut  "
	sql = sql & "		   			and gr.cod_bantotal = a.cod_bantotal  "
	sql = sql & "		   			and CONVERT(date,gr.desde) <= CONVERT(date,GETDATE())),0)as reemplazos_dot "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b  "
	sql = sql & "					inner join SUC_sucursal_guardias_r gr on gr.guardia_rut = b.guardia_rut and gr.cod_bantotal = b.cod_bantotal "
	sql = sql & "					where a.cod_bantotal = b.cod_bantotal and b.asistencia = 'si' and b.tipo_suc = 'reemplazo'  "
	sql = sql & "					and CONVERT(date,desde) <= CONVERT(date,GETDATE())),0) as reemp_p, "
	sql = sql & "		   isnull((select count(*) from SUC_sucursal_guardias_asistencia b  "
	sql = sql & "					inner join SUC_sucursal_guardias_r gr on gr.guardia_rut = b.guardia_rut and gr.cod_bantotal = b.cod_bantotal "
	sql = sql & "					where a.cod_bantotal = b.cod_bantotal and (b.asistencia = 'no' or b.asistencia is null) and b.tipo_suc = 'reemplazo' "
	sql = sql & "					and CONVERT(date,desde) <= CONVERT(date,GETDATE()) "
	sql = sql & "					),0) as reemp_a "
	sql = sql & "	from SUC_sucursal_guardias_t a "
	sql = sql & "	group by a.cod_bantotal,a.guardia_rut "
	sql = sql & ") as z ) as y  "
	sql = sql & ") as z "&sqlSuc&") as guardiasregistrados "
	sql = sql & ", "
	sql = sql & "(select sum(z.titulares_p)+SUM(z.reemp_p) from ( "
	sql = sql & "select *, case when y.total >= y.titulares_dot then 0 else y.titulares_a + y.reemp_a  end ausencia from ( "
	sql = sql & "select *, ((titulares_p)+(reemp_p)) as total from ( "
	sql = sql & "	select a.cod_bantotal,  "
	sql = sql & "		   count(*) titulares_dot "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b where a.cod_bantotal = b.cod_bantotal and b.asistencia = 'si' and b.tipo_suc = 'titular'),0) as titulares_p "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b where a.cod_bantotal = b.cod_bantotal and (b.asistencia = 'no' or b.asistencia is null) and b.tipo_suc = 'titular'),0) as titulares_a "
	sql = sql & "		   ,isnull((select COUNT(gr.guardia_rut_titular) "
	sql = sql & "		   			from SUC_sucursal_guardias_r gr  "
	sql = sql & "		   			where gr.guardia_rut_titular = a.guardia_rut  "
	sql = sql & "		   			and gr.cod_bantotal = a.cod_bantotal  "
	sql = sql & "		   			and CONVERT(date,gr.desde) <= CONVERT(date,GETDATE())),0)as reemplazos_dot "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b  "
	sql = sql & "					inner join SUC_sucursal_guardias_r gr on gr.guardia_rut = b.guardia_rut and gr.cod_bantotal = b.cod_bantotal "
	sql = sql & "					where a.cod_bantotal = b.cod_bantotal and b.asistencia = 'si' and b.tipo_suc = 'reemplazo'  "
	sql = sql & "					and CONVERT(date,desde) <= CONVERT(date,GETDATE())),0) as reemp_p, "
	sql = sql & "		   isnull((select count(*) from SUC_sucursal_guardias_asistencia b  "
	sql = sql & "					inner join SUC_sucursal_guardias_r gr on gr.guardia_rut = b.guardia_rut and gr.cod_bantotal = b.cod_bantotal "
	sql = sql & "					where a.cod_bantotal = b.cod_bantotal and (b.asistencia = 'no' or b.asistencia is null) and b.tipo_suc = 'reemplazo' "
	sql = sql & "					and CONVERT(date,desde) <= CONVERT(date,GETDATE()) "
	sql = sql & "					),0) as reemp_a "
	sql = sql & "	from SUC_sucursal_guardias_t a "
	sql = sql & "	group by a.cod_bantotal,a.guardia_rut "
	sql = sql & ") as z ) as y  "
	sql = sql & ") as z "&sqlSuc&") as guardiaspresentes "
	sql = sql & ", "
	sql = sql & "(select sum(z.ausencia) from ( "
	sql = sql & "select *, case when y.total >= y.titulares_dot then 0 else y.titulares_a + y.reemp_a  end ausencia from ( "
	sql = sql & "select *, ((titulares_p)+(reemp_p)) as total from ( "
	sql = sql & "	select a.cod_bantotal,  "
	sql = sql & "		   count(*) titulares_dot "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b where a.cod_bantotal = b.cod_bantotal and b.asistencia = 'si' and b.tipo_suc = 'titular'),0) as titulares_p "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b where a.cod_bantotal = b.cod_bantotal and (b.asistencia = 'no' or b.asistencia is null) and b.tipo_suc = 'titular'),0) as titulares_a "
	sql = sql & "		   ,isnull((select COUNT(gr.guardia_rut_titular) "
	sql = sql & "		   			from SUC_sucursal_guardias_r gr  "
	sql = sql & "		   			where gr.guardia_rut_titular = a.guardia_rut  "
	sql = sql & "		   			and gr.cod_bantotal = a.cod_bantotal  "
	sql = sql & "		   			and CONVERT(date,gr.desde) <= CONVERT(date,GETDATE())),0)as reemplazos_dot "
	sql = sql & "		   ,isnull((select count(*) from SUC_sucursal_guardias_asistencia b  "
	sql = sql & "					inner join SUC_sucursal_guardias_r gr on gr.guardia_rut = b.guardia_rut and gr.cod_bantotal = b.cod_bantotal "
	sql = sql & "					where a.cod_bantotal = b.cod_bantotal and b.asistencia = 'si' and b.tipo_suc = 'reemplazo'  "
	sql = sql & "					and CONVERT(date,desde) <= CONVERT(date,GETDATE())),0) as reemp_p, "
	sql = sql & "		   isnull((select count(*) from SUC_sucursal_guardias_asistencia b  "
	sql = sql & "					inner join SUC_sucursal_guardias_r gr on gr.guardia_rut = b.guardia_rut and gr.cod_bantotal = b.cod_bantotal "
	sql = sql & "					where a.cod_bantotal = b.cod_bantotal and (b.asistencia = 'no' or b.asistencia is null) and b.tipo_suc = 'reemplazo' "
	sql = sql & "					and CONVERT(date,desde) <= CONVERT(date,GETDATE()) "
	sql = sql & "					),0) as reemp_a "
	sql = sql & "	from SUC_sucursal_guardias_t a "
	sql = sql & "	group by a.cod_bantotal,a.guardia_rut "
	sql = sql & ") as z ) as y  "
	sql = sql & ") as z "&sqlSuc&") as guardiasausentes "
    
	'Response.Write(sql)
	'Response.End
	set rs = db.execute(sql)
	if not rs.eof then
	
	'=====================================================================
	' JSON
	'=====================================================================
	 Response.ContentType = "application/json"
	 
	 Response.Write "{"
	 Response.Write "  ""datos"": " 
	 Response.Write "{ "
	
	 Response.Write " ""cajerotitular"": """&rs("cajerotitular")&""", "
	 Response.Write " ""cajeroreemplazo"": """&rs("cajeroreemplazo")&""", "
	 Response.Write " ""cajeroadicional"": """&rs("cajeroadicional")&""", "
	 Response.Write " ""cajerosregistrados"": """&rs("cajerosregistrados")&""", "
	 Response.Write " ""cajerospresentes"": """&rs("cajerospresentes")&""", "
	 Response.Write " ""cajerosausentes"": """&rs("cajerosausentes")&""", "
	 Response.Write " ""asesortitular"": """&rs("asesortitular")&""", "
	 Response.Write " ""asesoreemplazo"": """&rs("asesoreemplazo")&""", "
	 Response.Write " ""asesoresregistrados"": """&rs("asesoresregistrados")&""", "
	 Response.Write " ""asesorespresentes"": """&rs("asesorespresentes")&""", "
	 Response.Write " ""asesoresausentes"": """&rs("asesoresausentes")&""", "
	 Response.Write " ""paramedicotitular"": """&rs("paramedicotitular")&""", "
	 Response.Write " ""paramedicoreemplazo"": """&rs("paramedicoreemplazo")&""", "
	 Response.Write " ""paramedicosregistrados"": """&rs("paramedicosregistrados")&""", "
	 Response.Write " ""paramedicospresentes"": """&rs("paramedicospresentes")&""", "
	 Response.Write " ""paramedicosausentes"": """&rs("paramedicosausentes")&""", "
	 Response.Write " ""guardiastitulares"": """&rs("guardiastitulares")&""", "
	 Response.Write " ""guardiasreemp"": """&rs("guardiasreemp")&""", "
	 Response.Write " ""guardiasregistrados"": """&rs("guardiasregistrados")&""", "
	 Response.Write " ""guardiaspresentes"": """&rs("guardiaspresentes")&""", "
	 Response.Write " ""guardiasausentes"": """&rs("guardiasausentes")&""" "
	
	 Response.Write "} }"		
	end if

%>